# Datei: webapps/nextcloud/docker-compose.yml
version: '3'
services:
  db:
    image: mariadb:10
    container_name: nextcloud_db
    networks:
      - nextcloud
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ciel5eeNgeez
      - MYSQL_PASSWORD=IeMaovahM2ba
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      
   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: nextcloud_pma
     links:
       - db
     environment:
       PMA_HOST: db
       PMA_PORT: 3306
       PMA_ARBITRARY: 1
     networks:
       -nextcloud
     restart: unless-stopped
     ports:
       - 8081:80
       
  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud_data:/var/www/html/data
    networks:
      -nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=IeMaovahM2ba
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      
  web:
    image: nginx:1
    container_name: nextcloud_web
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html
      - ./nextcloud_data:/var/www/html/data
    networks:
      - nextcloud
    restart: unless-stopped
        
volumes:
  db:
  nextcloud:
  
 networks:
   nextcloud:

